// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL07mqvPVcXWrlqhMkZewfnH3Azyef2i8',
    appId: '1:257642462839:web:b918a3b9f12ad6d976d072',
    messagingSenderId: '257642462839',
    projectId: 'ambient-4b28e',
    authDomain: 'ambient-4b28e.firebaseapp.com',
    storageBucket: 'ambient-4b28e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi5O-0cD-xZAYO1LkSQNdNkpMkHt5jQ7o',
    appId: '1:257642462839:android:c7d6c3b2574559cd76d072',
    messagingSenderId: '257642462839',
    projectId: 'ambient-4b28e',
    storageBucket: 'ambient-4b28e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqnsrLJJw3VsN8FMu3y8oQR2dv4HZ7w5U',
    appId: '1:257642462839:ios:ab6d964d3550ecd176d072',
    messagingSenderId: '257642462839',
    projectId: 'ambient-4b28e',
    storageBucket: 'ambient-4b28e.appspot.com',
    iosBundleId: 'com.example.ambient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqnsrLJJw3VsN8FMu3y8oQR2dv4HZ7w5U',
    appId: '1:257642462839:ios:ab6d964d3550ecd176d072',
    messagingSenderId: '257642462839',
    projectId: 'ambient-4b28e',
    storageBucket: 'ambient-4b28e.appspot.com',
    iosBundleId: 'com.example.ambient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL07mqvPVcXWrlqhMkZewfnH3Azyef2i8',
    appId: '1:257642462839:web:3ec9e5256b8d4b6976d072',
    messagingSenderId: '257642462839',
    projectId: 'ambient-4b28e',
    authDomain: 'ambient-4b28e.firebaseapp.com',
    storageBucket: 'ambient-4b28e.appspot.com',
  );
}
